spring.application.name=chess-backend

# Postgres and database config
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.clean-disabled=true

# Rabbitmq and queue config
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASS}

chess.rabbitmq.queue.analysis=game-analysis-queue
chess.rabbitmq.exchange.analysis=game-analysis-exchange
chess.rabbitmq.routing-key.analysis=game.analysis

chess.rabbitmq.queue.commentary=game-commentary-queue
chess.rabbitmq.exchange.commentary=game-commentary-exchange
chess.rabbitmq.routing-key.commentary=game.commentary

# AI related config
spring.ai.vertex.ai.gemini.project-id=${VERTEX_AI_PROJECT_ID:chess-review-ai}
spring.ai.vertex.ai.gemini.location=${VERTEX_AI_LOCATION:us-central1}
spring.ai.vertex.ai.gemini.chat.options.model=${VERTEX_AI_MODEL:gemini-2.0-flash}
spring.ai.vertex.ai.gemini.chat.options.temperature=${VERTEX_AI_TEMPERATURE:0.0}